import tkinter as tk
root = tk.Tk()
root.title("Course Selection")
root.geometry("300x300")
label1 = tk.Label(root, text="Select Courses")
label1.grid(row=0, column=0)
cb1 = tk.Checkbutton(root, text="Python")
cb1.grid(row=1, column=0)
cb2 = tk.Checkbutton(root, text="Java")
cb2.grid(row=2, column=0)
cb3 = tk.Checkbutton(root, text="C++")
cb3.grid(row=3, column=0)
label2 = tk.Label(root, text="Select Shift")
label2.grid(row=4, column=0)
rb1 = tk.Radiobutton(root, text="Morning", value=1)
rb1.grid(row=5, column=0)
rb2 = tk.Radiobutton(root, text="Afternoon", value=2)
rb2.grid(row=6, column=0)
rb3 = tk.Radiobutton(root, text="Evening", value=3)
rb3.grid(row=7, column=0)
root.mainloop()